### PR TITLE
add inlined fast-path to drop

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
not 100% sure we need this, but in theory this seems nice.

**Comment by epage** [comment]
I've played with outlining heap paths in `KString` (specifically, `clone`) but so far haven't seen any advantages.  However, I think this makes the code look nicer.

**Comment by ParkMyCar** [comment]
Let me add some benchmarks around drop so we can make a more clear decision on this

**Comment by ParkMyCar** [comment]
Thanks for the work here @matklad, sorry it took me so long to get back to this! I landed these changes in #78

**Pull request closed without merging**
