### PR TITLE
Fix: Added Code_Of_Conduct.md

### PR DESCRIPTION
**Pull request by Kalyanimhala**
Fixed  #339
Added code of conduct to the Repo.

Importance of Code Of Conduct - We propose adding a comprehensive Code of Conduct to our repository to ensure
 a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, 
and attracting a wider range of perspectives.

@neoeinstein  Kindly review it and merged the PR. Thank You!

### CODE REVIEW

**Comment by Kijewski** [comment]
My review: Stop spamming.

**Comment by ParkMyCar** [comment]
I appreciate the interest in `compact_str`! A code of conduct is definitely something that should be added, it's on my list to do. Unfortunately at the moment we're receiving an influx of PRs which simply update a few characters of the README. I'm unsure what caused the sudden increase, but given these PRs are relatively low impact, for the time being I'm going to close them under the idea that they're spam.

I sincerely apologize if this PR was opened in good faith, please don't allow this to discourage you from open source contributions in the future!

**Comment by Kijewski** [comment]
> I'm unsure what caused the sudden increase

https://blog.domenic.me/hacktoberfest/

**Comment by Kalyanimhala** [comment]
Thanks @ParkMyCar

**Pull request closed without merging**
